#!/usr/bin/ruby

CODE_MAP = {
"ACCT" => " CashCard/FlashPay Top-up (ATM)",
"ACO" => "Cashier's Order Equivalent",
"ACR" => "Accounting & Corporate Regulatory Authority",
"ACT" => "CashCard/FlashPay Top-up",
"ADJ" => "Adjustment",
"ADP" => "Deposit",
"ADV" => "Advice",
"ADVE" => " Error Correction of Advice",
"AFD" => "S$Fixed Deposit Placement",
"AG" => " Accountant General",
"AHL" => "Agency Housing Loan",
"AIC" => "Purchase International Calling Card",
"ATFEE" => "Account Fee",
"APC" => "CIRRUS Purchase",
"APP" => "Top-up Mobile Prepaid Card",
"AS" => " Purchase / Sale of Shares",
"ASC" => "PLUS Cash Withdrawal Service Charge",
"ASN" => "Associations",
"ATR" => "ATM Funds Transfer",
"AVA" => "Agri-food & Veterinary Authority of Singapore",
"AVIVA" => "Aviva Life Insurance",
"AWF" => "ATM Withdrawal Fee",
"AWL" => "Cash Withdrawal",


"BB" => " Baby Bonus Scheme",
"BILL" => " Bill Payment",
"BINT" => " Bonus Interest",
"BL" => " Custodian Service Charges",
"BLTL" => " Term Loan",
"BNK" => "Banks (financing loans,safe deposit box rental,etc)",
"BRCF" => " Revolving Credit Facility",
"BSTL" => " Short Term Loan",


"CAD" => "Corporate Actions - Local",
"CAF" => "Corporate Actions - Foreign",
"CAM" => "Cash Deposit Machine",
"CAN" => "Cancellation Transfer",
"CB" => " Postage Charge for Chq Bk",
"CBC" => "Foreign Cheques for Collection",
"CBC" => "A Foreign Cheques For Collection Agent Charges",
"CBC" => "C Foreign Cheques For Collection Comm & Charges",
"CBP" => "Foreign Cheques Purchased",
"CBP" => "A Foreign Cheques Purchased Agent Charges",
"CBP" => "C Foreign Cheques Purchased Comm & Charges",
"CCC" => "Credit Card Companies",
"CCO" => "Charitable Organisation",
"CCR" => "CashCard/FlashPay Refund",
"CCT" => "CashCard/FlashPay Top-up",
"CDC" => "Community Development Councils",
"CDE" => "ComfortDelGro Engineering Pte Ltd",
"CDF" => "Coin Deposit Fees",
"CDM" => "Deposit (Coin Deposit Machine)",
"CDP" => "Dividends/Cash Distribution",
"CES" => "Inland Revenue Authority of Singapore (Cess)",
"CFAF" => " Commitment Fee",
"CFC" => "ATM Card/CashCard Fee",
"CHD" => "Child Care Services",
"CHN" => "Donation",
"CHNE" => " Donation",
"CHQ" => "Cheque",
"CHQBK" => "Cheque Book Charge",
"CHQ-" => " Error Correction of Cheque",
"CHQ-L" => "Late Cheque",
"CHR" => "Returned Cheque",
"CHRE" => " Error Correction of Returned Cheque",
"CIS" => "Commercial & Industrial Security Corporation (CISCO)",
"CIV" => "CPF Investment Account Transaction",
"CL" => " Computer Loan",
"Claim" => "Dividend Claim",
"CLB" => "Private Clubs",
"CLFN" => " Term Loan",
"CLPA" => " Term Loan",
"CLPN" => " Term Loan",
"CLVA" => " Term Loan",
"CLVN" => " Term Loan",
"CLXA" => " Term Loan",
"CLXN" => " Term Loan",
"CML" => "Club Membership Loan",
"CO" => " Cashier's Order",
"CO" => "C  Cashier's Order Comm & Charges",
"COE" => "LTA COE Bidding",
"COS" => "CashCard Proceeds",
"CPF" => "Central Provident Fund Board",
"CPK" => "Carpark Charges",
"CPP" => "CashCard Purchase",
"CRA" => "CreditAssist",
"CRCF" => " Commitment Fee",
"CRE" => "Creation Transfer",
"CRPT" => " Commitment Fee",
"CSC" => "CIRRUS Cash Withdrawal Service Charge",
"CSH" => "Cash",
"CSL" => "Consolidated Amount for Unposted Transactions",
"CSTL" => " Commitment Fee",
"CTLF" => " Commitment Fee",
"CTU" => "Cash Top Up",
"CUS" => "Singapore Customs",
"CUT" => "Call Centre Unit Trust",


"D2P" => "D2Pay / eNETS transactions",
"DCR" => "Instant Direct Credit",
"DDBT" => " Instant Direct Debit",
"DED" => "Social Development Unit",
"DEFI" => " Interest",
"DEFP" => " Interest",
"DELAP" => "Delivery Against Payment",
"DINT" => " Overdraft Interest",
"DNT" => "Donations",
"DOS" => "Department of Statistics, Ministry of Trade and Industry",


"EC" => " Error Correction",
"ECM" => "E-Commerce Transactions",
"EDB" => "Economic Development Board",
"EHD" => "Environmental Health Department",
"ENV" => "Ministry of the Environment (all other payments)",
"EPS" => "Share Payment",
"EQM" => "Payments for equipment & machinery",
"ERS" => "ERS",
"ESA" => "IPO",
"EZF" => "Convenience Fee To EZ-Link Pte Ltd",
"EZT" => "ez-link Card Top-up",


"FAFY" => " Fixed Advance facility",
"FCA" => "Foreign Currency Current Account",
"FCD" => "Food Control Department",
"FCHL" => " Foreign Currency Housing Loan",
"FCI" => "FC Fixed Deposit Interest/Structured Deposit Payout",
"FD" => " FD Placement",
"FDC" => "CPF Minimum Sum Monthly Instalment Payment",
"FDD" => "S$ Fixed Deposit/Structured Deposit Placement",
"FDI" => "S$ Fixed Deposit Interest/Structured Deposit Payout",
"FDP" => "S$ Fixed Deposit/Structured Deposit Principal Amount",
"FDW" => "S$ Fixed Deposit/Structured Deposit Principal Amount",
"FEE" => "Instant Direct Debit Fee",
"FFD" => "FC Fixed Deposit/Structured Deposit Placement",
"FIN" => "Finance Companies",
"FSA" => "Further StudyAssist",
"FWL" => "Central Provident Fund Board (Foreign Workers' Levy)",
"FXG" => "Hedging Gain",
"FXL" => "Hedging Loss",


"GAS" => "Petroleum (use of card issued by petroleum cos)",
"GC" => " GST Credits",
"GD" => " Growth Dividend",
"GNIF" => " Guaranteed Notes Issuance Facility",
"GO" => " Garnishee Order",
"GR" => " GIRO",
"GSI" => "S'pore Government Securities Interest",
"GSP" => "S'pore Government Securities Principal",
"GST" => "Inland Revenue Authority of Singapore (GST)",
"GTR" => "Fund transfer from linked SA to CA",
"GVR" => "Gift Voucher",


"HAD" => "Ministry of the Environment (Hawkers Dept)",
"HCCT" => " CashCard Top Up (HomeNETS)",
"HCT" => "HomeNETS CashCard Top-up",
"HDB" => "Housing & Development Board",
"HDS" => "Home Delivery Services",
"HHL" => "HDB Housing Loan",
"HL" =>  "Mortgage Loan",
"HLFN" => " Term Loan",
"HLPA" => " Term Loan",
"HLPN" => " Term Loan",
"HLVA" => " Term Loan",
"HLVN" => " Term Loan",
"HLXA" => " Term Loan",
"HLXN" => " Term Loan",
"HOS" => "Hospitals",
"HP" => "Hire Purchase",
"HPN" => "Handphone",
"HSC" => "HomeNETS CashCard Top-up Service Charge",

"IBAS" => " Settlement of Securities by Investor Services",
"IBG" => "Interbank GIRO",
"ICS" => "Premium for Fire Insurance Policy",
"ICSG" => " General Insurance",
"ICSL" => " Life Insurance",
"IFD" => "S$Fixed Deposit Placement",
"ILFN" => " Term Loan",
"ILPA" => " Term Loan",
"ILPN" => " Term Loan",
"ILVA" => " Term Loan",
"ILVN" => " Term Loan",
"ILXA" => " Term Loan",
"ILXN" => " Term Loan",
"INS" => "Insurance",
"INSTS" => "Insurance-TravellerShield",
"INT" => "Interest Earned",
"INV" => "Investment (eg. unit trust, growth funds, bonds, etc)",
"IOF" => "Investment of Funds",
"IRA" => "Tax Due to IRAS",
"ITR" => "Internet Banking Funds Transfer",
"ITT" => "Inward Telegraphic Transfer",
"ITT" => "C Inward Telegraphic Transfer Comm & Charges",
"ITX" => "Income Tax",


"JTC" => "Jurong Town Corporation",


"LCA" => "Leverage Currency Account",
"LCDP" => " Leverage Currency Account Deposit",
"LCLN" => " Leverage Currency Account Loan",
"LOD" => "Min. of Law - Land Office Dept",
"LTA" => "Land Transport Authority",


"MAG" => "Payments for Magazines & Publications subscriptions",
"MAS" => "Monetary Authority of Singapore",
"MBL" => "Singapore Telecom Mobilelink Pte Ltd",
"MC" => "Management Corporation",
"MCD" => "Ministry of Community Development",
"MCO" => "Monthly Savings Amount for MySavings Account",
"MDA" => "Media Development Authority of Singapore",
"MED" => "Medical Services and equipment",
"MEP" => "MEPS Payment",
"MEP" => "C MEPS Payment Comm & Charges",
"MER" => "MEPS Receipt",
"MER" => "C MEPS Receipt Comm & Charges",
"MGT" => "Management Fees",
"MOE" => "Ministry of Education",
"MOF" => "Ministry of Finance",
"MOH" => "Ministry of Health",
"MOL" => "Ministry of Labour",
"MPA" => "Maritime Port Authority",
"MSA" => "Debit Card Annual Fee",
"MSC" => "Miscellaneous",
"MSCE" => " Error Correction of Miscellaneous",
"MSM" => "Debit Card Misc",
"MSR" => "Debit Card Replacement",
"MST" => "Debit Card Transaction",


"NCD" => "Cash Deposit Others",
"NCHG" => " Custody related charges",
"NDF" => "Cash Deposit Others Service Charge",
"NDIV" => " Dividend Payment (by SFS Ops)",
"NET" => "Network For Electronics Transfers (NETS)",
"NEW" => "Newspaper Subscription",
"NIF" => "Notes Issuance Facility",
"NINT" => " Interest Payment (by SFS Ops)",
"NPW" => "Purchase with Cash Withdrawal",
"NSEC" => " Corporate Actions related Payment (by SFS Ops)",
"NSS" => "NSS-New Singapore Shares",
"NWL" => "Cash Withdrawal Others",


"OA" => "Official Assignee",
"ODD" => "Outward Demand Draft",
"ODD" => "C Outward Demand Draft Comm & Charges",
"OSA" => "Overseas StudentAssist",
"OTT" => "Outward Telegraphic Transfer",
"OTT" => "A Outward Telegraphic Transfer Agent Charges",
"OTT" => "C Outward Telegraphic Transfer Comm & Charges",


"PAY" => "Salary",
"PGL" => "Singapore Telecom Pagelink Pte Ltd",
"PGR" => "Pager",
"PL" => "Personal Loan",
"POS" => "Point-of-Sale Transaction",
"PPD" => "Primary Production Dept",
"PPF" => "Youth Olympic Games Prepaid Card Convenience Fee",
"PPR" => "Youth Olympic Games Prepaid Card Refund",
"PPT" => "Youth Olympic Games Prepaid Card Top Up",
"PS" => "Power Supply",
"PSA" => "Port of Singapore Authority",
"PSC" => "Public Service Commission",
"PTA" => "POSBkids-Trust Account",
"PTR" => "Requisition Fees Property Tax Department",
"PTX" => "Property Tax",
"PUB" => "Public Utilities Board",
"PWD" => "Public Works Department",


"QCD" => "Quick Cheque Deposit",
"QCDE" => " Error Correction of Quick Cheque Deposit",
"QCDM" => " Quick Cheque Deposit",
"QWA" => "Advice Withdrawal (Counter ATM Card-Operated Trans)",
"QWC" => "Cash Withdrawal (Counter ATM Card-Operated Trans)",


"RAF" => "Revolving Advance Facility",
"RASC" => " Regional Cash Withdrawal Service Charge",
"RCF" => "Revolving Credit Facility",
"RCFN" => " Revolving Credit Facility",
"RCM" => "Refuse and Cleansing Maintenance Services",
"RCPN" => " Revolving Credit Facility",
"RECAP" => "Receipt Against Payment",
"RED" => "Donation",
"RFT" => "Regional Funds Transfer",
"RTF" => "C Remittance Transfer of Funds Comm & Charges",
"R-GR" =>  "GIRO Return",
"RIS" => "Retail Instalment Scheme",
"RL" =>  "Renovation Loan",
"RPT" => "Reports",
"RRCF" => " Risk Participation",
"RSC" => "Rights Application CDP Charge",
"RSF" => "IPO Financing A/c Fund Transfer - Rev",
"RTD" => "Reg. Of Land Titles & Deeds",
"RTF" => "Remittance Transfer of Funds",
"RTL" => "Rental",
"RTLN" => " Risk Participation",
"RTR" => "Returned Interbank Funds Transfer",
"RTS" => "Rights",
"RUF" => "Revolving Underwriting Facility",
"RWDL" => " Regional Cash Withdrawal",

"SAL" => "Salary",
"SALES" => "Sales At ATM",
"SBA" => "Singapore Broadcasting Authority",
"SC" => " Service Charge",
"SC-FS" => "Service Charge - Statement of Financial Standing",
"SC-RG" => "Service Charge - Return GIRO",
"SC-SI" => "Service Charge - Standing Instruction",
"SCB" => "Board of Commissioners of Currency, Singapore",
"SCF" => "Staff Course Financing Loan",
"SCH" => "Schools",
"SCL" => "Staff Computer Loan",
"SCTR" => " Service Fee-Treasures",
"SCV" => "Singapore Cable Vision",
"SDA" => "Structured Deposit ATM Application",
"SDB" => "Singapore Dental Board",
"SDR" => "Safe Deposit Box",
"SEC" => "Security Houses",
"SEW" => "Ministry of the Environment (Sewerage Dept)",
"SF" => " IPO Financing A/c fund Transfer",
"SGI" => "SAF Personnel Services Centre",
"SGR" => "Refund arising from SGS Discount/Premium",
"SGS" => "Singapore Government Securities (SGS) Application",
"SGSI" => " S'pore Government Securities Interest",
"SGSP" => " S'pore Government Securities Principal",
"SGT" => "Refund arising from SGS Tender",
"SHG" => "Self-Help Groups- (eg.CDAC,Eurasian Assn,Mendaki and Sinda)",
"SHHL" => " Staff HDB Housing Loan",
"SHL" => "Staff Housing Loan",
"SHR" => "Share Transaction",
"SHUB" => " Top-up StarHub Prepaid Card",
"SI" => " Standing Instruction",
"SL" => " Student Loan",
"SLA" => "Singapore Land Authority",
"SMC" => "Singapore Medical Council",
"SMT" => "Singapore Mint",
"SNB" => "Singapore Nursing Board",
"SNS" => "Singapore Network Services",
"SOC" => "Society",
"SPB" => "Singapore Pharmacy Board",
"SPL" => "Staff Personal Loan",
"SPS" => "SP Services Ltd",
"SRL" => "Staff Renovation Loan",
"SRS" => "Supplementary Retirement Scheme",
"ST" => " Singapore Telecom",
"STAF" => " Short Term Advance Facility",
"STC" => "Singapore Turf Club",
"STF" => "Short Term Facilities",
"STFA" => " Short Term Loan",
"STL" => "Staff Top-Up Loan",
"STLN" => " Short Term Loan",
"STN" => "Fixed Income Securities",
"STPA" => " Short Term Loan",
"STPN" => " Short Term Loan",
"STY" => "Study Loan",
"SVCH" => " Service Charge",
"SVL" => "Staff Vehicle Loan",
"SW" => " Switching Funds",
"SYE" => "Save-As-You-Earn Account",


"TC" => " Town Councils",
"TCA" => "Training Commitment Award",
"TCC" => "Concession Card Top Up",
"TCF" => "Concession Card Top Up Convenience Fee",
"TCT" => "CashCard/FlashPay Top-up",
"TDB" => "Trade Development Board",
"TFAV" => " Aviva Life Insurance",
"TFD" => "S$Fixed Deposit Placement",
"TFL" => "Tuition Fee Loan",
"TL" => " Term Loan",
"TLFN" => " Term Loan",
"TLG" => "Transit Link",
"TLPA" => " Term Loan",
"TLPN" => " Term Loan",
"TLVA" => " Term Loan",
"TLVN" => " Term Loan",
"TLXA" => " Term Loan",
"TLXN" => " Term Loan",
"TM1" => "Top-up M Card Voucher at ATM",
"TPQ" => "Traffic Police",
"TRFA" => " Settlement of Outstanding Cashline Bill",
"TRFC" => " Settlement of Outstanding Credit Card Bills",
"TRS" => "Trusts Services",
"TTR" => "Funds Transfer",
"TUP" => "Top-Up Loan",


"UMC-S" => "POSB GO! Debit Card transaction",
"UMCS" => " POSB GO! Debit Card replacement fee",
"UMS" => "Union Membership",
"UPD" => "Update on Latest Balance",
"URA" => "Urban Redevelopment Authority",
"UTA" => "Unit Trust Application",
"UTAA" => " Unit Trust Application",
"UTR" => "Redemption of Units",
"UTSA" => " Unit Trust Application",


"VEH" => "Vehicles - rental,finance or lease",
"VL" => " Car Financing",
"VM" => " Virgin Mobile Top-Up",


"WIS" => "Workfare Income Supplement Scheme",
"WSB" => "Workfare Special Bonus",
"WT" => " FD Withdrawal",
"WTAX" => " Withholding Tax",


"YINT" => " Total Interest Earned in a Year"
}